### ISSUE TITLE
feed and atom issue

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#31]
okay say that I've just written and published a titled post of "Hello World", the url to view that article would be http://example.com/post/hello-world but say if I attempted to view the article from the atom/feed it would direct the user towards http://example.com/hello-world leaving /post/ out of the url and rendering a blank page

**Comment by 9uuso** [comment]
Thanks for filing this issue! I haven't written tests for checking the output of the RSS feeds, but I'll surely do that later. Anyhow, the URL issue is now fixed. Please pull the master to apply the changes.
