### ISSUE TITLE
login/register links while signed-in

### ISSUE THREAD

**Issue by ghost** [9uuso/vertigo#32]
okay, another issue which I've notice is that when you are logged in you are still able to see the login/register links on the index page. Is there a way to change this so that the links are only displayed when the user isn't signed in.

**Comment by 9uuso** [comment]
Currently I'm not aware of way to add this, expect for writing a middleware and modifying every render call in routes...

Look forward to #27, it will most likely added in there.

**Comment by jayrox** [comment]
you can fix this easily.

in the template add something like:

{{ if loggedin .Session }}
	<a href="/user">User</a>
	<a href="/user/logout">Log out</a>
{{ else }}
	<a href="/user/login">Log in</a>
	{{ if allowregistrations . }}<a href="/user/register">Register</a>{{ end }}
{{ end }}

and in main.go add a "loggedin" template helper:

"loggedin": func(session sessions.Session) bool {
	return sessionIsAlive(session)
},

**Comment by jayrox** [comment]
i know that actually ends up being a ton of updates and changes but it adds a ton of power.

**Comment by 9uuso** [comment]
Thanks @jayrox. The method you described is the same to what I've resorted to use in other apps. Though, I hope this could achieved in some easier way.

I'm going to replace martini with negroni or gin soon, which might give new ways to resolve this problem. In general, the barebones HTTP middleware used by negroni and gin should be a lot more versatile. I'll try to find the time to check up on this during the next week, during which I'll also be merging the database-as-drivers branch. After that getting rid of martini should be pretty straightforward.

Also, @jayrox, any comments on the database-as-drivers branch are welcome. Should you find anything which bothers your mind, let me know about it on #25. I'll probably end up creating an organization for the database plugins, which will then be imported as git submodules on this repository.

**Comment by jayrox** [comment]
i've been working on replacing martini and have it basically working except the tests.

**Comment by 9uuso** [comment]
@jayrox I added you as a collaborator. I will soon merge the database-drivers branch to the master. I would then like you to fork it and apply the changes regarding martini into a new branch. I could check up on any issues you might have with the tests. The tests itself do not have anything martini specific, so if the server works as a normal HTTP server, everything should be about fine.

I will reference the commits to this issue once I push any code.

**Comment by netbun** [comment]
@9uuso I didn't want to start another issue for this, but shouldn't vertigo have a way in which themes can simply be implemented such as Ghost or Wordpress? This is possibly around the same bout, shouldn't we add a default theme for the blog and then a separate for the admin type section.

**Comment by jayrox** [comment]
ideally with these little helpers themes will be very doable.

if you look at my fork (the version i use to host my personal copy) you can see some of the helpers i've added.

my version uses [polymer](https://www.polymer-project.org/0.5/) which pretty much shows you can do anything you want theme wise. if there is any interest we can certainly look into merging some, any or all of these changes to this repo.

**Comment by netbun** [comment]
@jayrox your example code above is initially the thing that should be implemented before anything else, is it already committed onto your forked source?

**Comment by jayrox** [comment]
Yes

**Comment by 9uuso** [comment]
> I didn't want to start another issue for this, but shouldn't vertigo have a way in which themes can simply be implemented such as Ghost or Wordpress?

Yes, this is a feature I've thought about earlier.

That being said, [journey](https://github.com/kabukky/journey) did integrate Ghost themes into their engine (which is interesting and appealing feature) which Vertigo could benefit as well. However, I'm afraid it would introduce too much restrictions on what you can and what you can't do with templates. In addition, the way the Ghost templates are parsed looks [rather complicated to me](https://github.com/kabukky/journey/blob/master/templates/generation.go).

If the functionality would be imported as a nice package, which would work nicely with `html/template`, then it might be a different thing.

> This is possibly around the same bout, shouldn't we add a default theme for the blog and then a separate for the admin type section.

The blog and admin section do not need separate themes.

However, themes should be able to override default templates, provide helper functions in Go and override or provide their own CSS and JS. Doing this will require some modifications at least to the settings, so its not all too straightforward. Although, implementing this feature now would not be a gigantic effort either, so I'll have a look at it as soon as I find the time and willingness.

@jayrox I'll check out your repo and I find any code to merge, I'll setup a new branch.

**Comment by 9uuso** [comment]
This will be "fixed" with a single User CP link which leads to login page (/user) if you are logged in. If you are not logged in, you should see a register link where you can register.

**Comment by 9uuso** [comment]
I decided to keep the RSS logo in the base theme.

PostgreSQL integration is only one bug away.
