### ISSUE TITLE
error handler and submit button

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#34]
when I direct myself towards a unknown page such as http://example.com/sdfdsfasd, I begin see a blank page which a 404 naturally should really be displayed instead and other errors such as 200, 401, 500 etc. Martini should have this built-in so idk why it's not rendering via vertigo. Another thing is when writting a post, I'd recommend some sort of submit button.

**Comment by 9uuso** [comment]
The 404 error handler should now work.

You can submit a post by pressing enter on the title when you are done. This is basic browser behavior, which is supported by every device I've tested it with.

Having no visible submit button is ultimately a tradeoff between looks and what's natural to the user. Given that most users seem to be unaware of the enter-to-submit behavior, I guess I need to add the submit button back to the page.

**Comment by 9uuso** [comment]
That being said, what's your input on this? Also, @jayrox, I'd value your opinion on this.

**Comment by netbun** [comment]
@9uuso I mean, the atmosphere of not having a submit button is great but within a few hours of first using vertigo I was having a rough time attempting to save the my newly written articles

**Comment by 9uuso** [comment]
Alright, I'll add the submit button for the sake of convenience.

**Comment by jayrox** [comment]
i'd suggest a submit button. its not obvious to many users that hitting enter on the subject would submit the post.
