### ISSUE TITLE
time issue

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#37]
I pulled the latest code and deployed it to heroku, I submitted a new post but the time was a little wrong. I posted my post at 6:45 AM but it displays 10:45AM. I don't know if this is set for your time but can you confirm? @9uuso

**Comment by 9uuso** [comment]
Post creation time is an UNIX timestamp. The database driver declares it as such: [databases/gorm/posts.go#L53](https://github.com/9uuso/vertigo/blob/master/databases/gorm/posts.go#L53)

This formatted time is controlled by [main.go#L72-L74](https://github.com/9uuso/vertigo/blob/master/main.go#L72-L74)

What this means is that the time is most likely taken from the Heroku's server time, which seem to be the time of Ireland.

If you can confirm that the time difference between you and Ireland is 4 hours, I could take a further look into the bug.

**Comment by netbun** [comment]
@9uuso yeah, theres a 5 hour difference

**Comment by 9uuso** [comment]
As far as I know, there is no way to feed the server your current time without using JS. I have to figure if I need to implement a select option to choose your timezone.

**Comment by netbun** [comment]
@9uuso well if the select option is the simplest way to do this then I guess that it doesn't sound bad, :+1:

**Comment by jayrox** [comment]
a timezone select option is probably the best option. just dont forget to
keep the timezone data stored as utc

**Comment by 9uuso** [comment]
branches merged
