### ISSUE TITLE
Markdown as default post format

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#38]
This is convenient since html isn't highly being used for blog posting any more, most traditional blogging engines and platforms have switched to markdown as there default format. If this was a valid change, wouldn't you only have to change the radio value on settings.tmpl?

**Comment by 9uuso** [comment]
Yes, this is probably a change I need to change in some future version. The change is ultimately just a few lines, but the tests have to be updated as well.

**Comment by netbun** [comment]
@9uuso nice 👍

**Comment by 9uuso** [comment]
The initial work has now been done, I should land a commit on the dev branch in a few days.

**Comment by netbun** [comment]
@9uuso great to hear this, can't wait till it's fully featured in vertigo

**Comment by 9uuso** [comment]
This feature is now merged in `dev` branch. Feel free to try it out.

I'll close this ticket once I'll merge the branch into master.

**Comment by 9uuso** [comment]
branched merged
