### ISSUE TITLE
commenting system or pure medium-style?

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#39]
As you can tell, medium doesn't have any type of commenting-system embedded but it would be simple to add in vertigo. It would only take a discus input field in the settings to implement a pretty decent commenting interface via disqus but do you think it's necessary?

**Comment by 9uuso** [comment]
[Jay's fork](https://github.com/jayrox/vertigo) already has it. If you can fork the current master branch and add the feature to it, then sure, I'll accept the PR.

Then again, Disqus does not necessarily need a backend modifications, which I'd rather keep to bare minimum. Therefore, if you alternatively want to write a wiki page how to add Disqus's JS snippet onto the templates, I'd be happy as well.

**Comment by netbun** [comment]
@9usso I'll be sure to keep this in consideration, I will pr all necessary changes above after school 👍

**Comment by jayrox** [comment]
Yea, its not really required to be added to the core. I only added it
because i think it was easier that way to maintain
