### ISSUE TITLE
Search and clauses

### ISSUE THREAD

**Issue by 9uuso** [9uuso/vertigo#40]
Currently the search does not work if you search with clauses instead of single word.

This is unexpected behavior.

**Comment by jayrox** [comment]
example?

**Comment by 9uuso** [comment]
Search "Blocking does not work anymore in the recent versions of" on my [blog](https://www.juusohaavisto.com/)

**Comment by jayrox** [comment]
hmm are you sure its not something else causing than a clause.

examples:
"Blocking" - returns 3 results
"Blocking does" - returns 1
"Blocking html" - returns 1
"Blocking html links" - returns 0

seems i cant do any searches with 3 or more words in the search field. is something possibly trimming the search query?

**Comment by 9uuso** [comment]
It's lack of features which is causing this.

In [posts.go](https://github.com/9uuso/vertigo/blob/master/posts.go#L50) where the Get method is declared the contents of each published post is iterated word by word to achieve fuzzy search. This is beneficial if you are only using a single keyword to find content. For example, if you search for 'twatch' instead of 'twitch' on my blog, you will still get the Twitch post as a result, even though the post does not actually contain the keyword (this is also the reason why I do not plan to add tags or hashtag options to posts).

But when you give it more words than one, the fuzzy search algorithm does not work, since it is meant to compare single words. Searching for "Blocking does not work anymore in the recent versions of" will eventually compare "Blocking" with "Blocking does not work anymore in the recent versions of", which breaks the algorithm since the second phrase is so long.

This could be fixed by first searching the phrase as it is given by the user, after which it will run fuzzy search if nothing is found.

However, I'd prefer not to mimic Google too much, since that's what the user will ultimately use anyway if they do not find the content they are looking for.

Whether it is common for users to search content from blogs with specific keywords happens to be something I do not have much data of, but I'd guess it would be rather rare.

I'd rather hold on to the search functionality since it is one feature a dynamic blog can offer over a static one, without resorting to embedded Google search.

**Comment by jayrox** [comment]
what are the cons to just running both search methods? if fuzzy returns zero results, run full search. the full search could even be handled by the sql engine which would likely be faster than loading all of the entries into the go app and then iterating the subjects and bodies for the string.

something like 

     SELECT * FROM posts WHERE subject LIKE "%query%" OR body LIKE "%query%"

thats not exactly right but leads to the right idea i believe.

**Comment by 9uuso** [comment]
I'll look into how I could leverage the DB on this. Your suggestion sounds good to me.

**Comment by 9uuso** [comment]
I've been developing [the underlying algorithm package](https://github.com/9uuso/go-jaro-winkler-distance). The changes to the actual search routes are still undone, as the conversion to idiomatic HTTP stack seems to require a lot more attention than I initially thought.

**Comment by jayrox** [comment]
does the code in the alice repo help at all with the idiomatic routes?

**Comment by 9uuso** [comment]
It will let me just copy-and-paste code from the repo, which will speed things up a lot. Thank you for that.

However, before that I'd like to finalize #37. I got tests to pass on `dev` branch yesterday, which means I can start working on #37 next. After that I'll merge the alice branch and handle this issue. After those things I can start looking at a new public release.

**Comment by jayrox** [comment]
i can help with #37, i'll look at it a bit today if a get a chance

**Comment by 9uuso** [comment]
Cool, I'd appreciate that. :+1:

**Comment by 9uuso** [comment]
@jayrox Have you had the time to start the merge? I'll start it in a new branch unless you already have.

**Comment by jayrox** [comment]
i placed my files in the timezone branch, if you to look it over before merge. last time i checked it looked like it could be merged without issue

**Comment by 9uuso** [comment]
Oh, I somehow mixed the issues.

I'll start looking at #27 next. I'll use the alice repo as the base for that. Expect new branch in a few days.

**Comment by jayrox** [comment]
sounds good, the code regarding the timezone was based on the martini
version but it shouldnt take much to move it over. i'm currently in another
state for work until thursday. if i get some time i'll try to look at
moving it to the alice branch. if your fork up to date? i'll clone it and
get to work on that.

**Comment by 9uuso** [comment]
Though I'm going to try develop my own rendering library if that's what's needed to get .LoggedIn helpers etc to work well.

**Comment by jayrox** [comment]
Check the Alice repo, the logging stuff works.. I have it commented out
cause I was trying to get the tests to pass

**Comment by 9uuso** [comment]
probably wisest to use this: https://github.com/blevesearch/bleve
