### ISSUE TITLE
installation from source issues

### ISSUE THREAD

**Issue by netmml** [9uuso/vertigo#45]
I attempted to install vertigo via source exactly as detailed, it seemed as if the packages where needed to be installed first. So I then attempted `go get github.com/9uuso/vertigo` then later cloned the source and ran `godep go build` and `PORT="80" MARTINI_ENV="production" ./vertigo` which everything then seemed to run as planned. Maybe `go get github.com/9uuso/vertigo` should be added alongside of `go get github.com/tools/godep` in the readme?

**Comment by 9uuso** [comment]
I'm unable to reproduce this. Therefore, I'd need you to answer these questions:

What's your platform?
Whats your Go version?
Does running `go get -u github.com/tools/godep` fix this?
Do you get any errors? If you do, what?
Does running `godep go build ./...` fix this issue?

To my understanding running `go get github.com/9uuso/vertigo` should not affect anything, since ultimately the vendored packages in the Godeps folder will be used anyway.

However, take your time to answer the questions provided. Before that I won't start speculating too much.

**Comment by netmml** [comment]
@9uuso I seem to get this error everytime, 

```
main.go:9:2: cannot find package "github.com/9uuso/vertigo/databases/gorm" in any of:
	/home/netmml/.gvm/gos/go1.4/src/github.com/9uuso/vertigo/databases/gorm (from $GOROOT)
	/home/netmml/Desktop/vertigo/Godeps/_workspace/src/github.com/9uuso/vertigo/databases/gorm (from $GOPATH)
	/home/netmml/Desktop/go/src/github.com/9uuso/vertigo/databases/gorm
main.go:10:2: cannot find package "github.com/9uuso/vertigo/misc" in any of:
	/home/netmml/.gvm/gos/go1.4/src/github.com/9uuso/vertigo/misc (from $GOROOT)
	/home/netmml/Desktop/vertigo/Godeps/_workspace/src/github.com/9uuso/vertigo/misc (from $GOPATH)
	/home/netmml/Desktop/go/src/github.com/9uuso/vertigo/misc
main.go:11:2: cannot find package "github.com/9uuso/vertigo/routes" in any of:
	/home/netmml/.gvm/gos/go1.4/src/github.com/9uuso/vertigo/routes (from $GOROOT)
	/home/netmml/Desktop/vertigo/Godeps/_workspace/src/github.com/9uuso/vertigo/routes (from $GOPATH)
	/home/netmml/Desktop/go/src/github.com/9uuso/vertigo/routes
main.go:12:2: cannot find package "github.com/9uuso/vertigo/settings" in any of:
	/home/netmml/.gvm/gos/go1.4/src/github.com/9uuso/vertigo/settings (from $GOROOT)
	/home/netmml/Desktop/vertigo/Godeps/_workspace/src/github.com/9uuso/vertigo/settings (from $GOPATH)
	/home/netmml/Desktop/go/src/github.com/9uuso/vertigo/settings
godep: go exit status 1
```

also my go version is 1.4.2 and os is ubuntu but does also does same on windows 8

**Comment by 9uuso** [comment]
Does running `godep go build ./...` fix it?

If that does not cut it, the `go get github.com/9uuso/vertigo` should indeed be added.

However, the command should probably be `go get -u github.com/9uuso/vertigo` so that the package is always updated.

**Comment by netmml** [comment]
@9uuso I attempted `godep go build ./...` which didn't work, and that sounds good

**Comment by 9uuso** [comment]
Want to issue PR on this?

**Comment by netmml** [comment]
@9uuso :+1:
