### ISSUE TITLE
posts per page/pagination

### ISSUE THREAD

**Issue by netmml** [9uuso/vertigo#47]

**Comment by 9uuso** [comment]
This is marked in #1, which links to https://00f.net/2011/02/25/pagination-and-http-caching/. Some sort of implementation endorsed by the blog post will most likely be implemented.

In the future, if you'd like to start a new issue on some new feature, I'd be interested in hearing how *you* would implement such feature.

That being said, I probably need to bring up the old gitter room up. Conversations on features are starting to get scrambled on irrelevant issues. If you want to chit-chat on features and what-not, feel free to visit: https://gitter.im/9uuso/vertigo

I'll receive email alerts even if I would be away.
