### ISSUE TITLE
Effort to compile Vertigo on Windows dev box fails

### ISSUE THREAD

**Issue by JanSichula** [9uuso/vertigo#52]
Hello,

I was able to install Vertigo on Heroku through the button publish but when I try to produce a local build of Vertigo on my Win 8.1 Pro x64 dev box preferably with Sqlite, it ends with a following error message.  

c:\Inetpub\GoLanguage\src\github.com\9uuso\vertigo>go build
# github.com/9uuso/vertigo
C:\Inetpub\GoLanguage\src\github.com\9uuso\vertigo\main.go:68: cannot use timezone.Locations (type []timezone.Timezone)
as type [416]timezone.Timezone in return argument

I am using Go version 1.4.2. Any advice will be highly appreciate.

**Comment by 9uuso** [comment]
Does running `godep get ./ && godep go build` in `C:\Inetpub\GoLanguage\src\github.com\9uuso\vertigo` result in error as well?

**Comment by JanSichula** [comment]
Uch, my fault that I have omitted godep get ./ but still no luck. Here is the output:

c:\Inetpub\GoLanguage\src\github.com\9uuso\vertigo>godep get ./ && godep go build
# github.com/9uuso/vertigo/routes
routes\posts.go:10: inconsistent definition for type render.Render during import
        interface { Data(int, []byte); Error(int); HTML(int, string, interface {}, ...render.HTMLOptions); Header() http
.Header; JSON(int, interface {}); Redirect(string, ...int); Status(int); Template() *"html/template".Template; XML(int,
interface {}) } (in "github.com/martini-contrib/render")
        interface { Data(int, []byte); Error(int); HTML(int, string, interface {}, ...render.HTMLOptions); Header() http
.Header; JSON(int, interface {}); Redirect(string, ...int); Status(int); Template() *"html/template".Template; Text(int,
 string); XML(int, interface {}) } (in "github.com/9uuso/vertigo/misc")
godep: go exit status 2
godep: exit status 1

**Comment by 9uuso** [comment]
Are you running on `dev` tree? The render library on it is WIP.

If that is the case, try cloning the master branch instead.

**Comment by 9uuso** [comment]
I'll close this for now. Let me know if you still face problems.
