### ISSUE TITLE
issue on addons

### ISSUE THREAD

**Issue by nikhil009** [9uuso/vertigo#53]
Hi,
It seems that for heroku the app requires a credit card, when you deploy it any app . Anyone experienced this? how to overcome on this issue.

**Comment by 9uuso** [comment]
See #8.

> As I said, I do not know why they require an credit card to deploy. However, you can try if the reason is Mailgun by forking the repository and deleting "addons": [ "mailgun" ], from the app.json in the project root folder. Once you have committed your changes to Github, just click on the Deploy button and see if it works any different.

> They may be requiring credit card because with the free plan of Mailgun you can only send 300 emails or less per day. I haven't used Heroku in production, so I do not know whether the plan would automatically scale for a bigger one should the limit be broken.

> Mailgun is not really needed for Vertigo to function, so should you try the scheme I described above, you can just insert placeholder text to the Mailgun fields. The password reminder function won't work, but everything else should.

So, forking the project, removing the `"addons": [ "mailgun" ], from the app.json` and push the changes. Then navigate to your forked project and click the heroku deploy button. That should do the trick.

Further reading on Heroku: [Advanced Heroku deployment](https://github.com/9uuso/vertigo/wiki/Advanced-Heroku-deployment)

**Comment by nikhil009** [comment]
Thanks for reply . But this solution is previous one and older. In my repository there is no app.json file. So Please have a look on. https://github.com/nikhil009/voicechat  so what should i do ?

**Comment by 9uuso** [comment]
I guess you meant to link https://github.com/nikhil009/vertigo

Anyhow, it should not require credit card. Are you sure you are not trying to create your sixth free app? All the restrictions are listed [here](https://devcenter.heroku.com/articles/account-verification#when-is-verification-required).

**Comment by nikhil009** [comment]
Ok. thanks for reply. even i post my issue on this.

**Comment by 9uuso** [comment]
Closing for now. If you have any more questions, feel free to re-open.
